apiVersion: v1
kind: Service
metadata:
  name: mvn-old-template
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 10294
    protocol: TCP
  type: NodePort
  selector:
    app: mvn-old-template
