apiVersion: v1
kind: Service
metadata:
  name: nodejs-template
spec:
  ports:
  - name: http
    port: 6020
    targetPort: 6020
    nodePort: {{nodePort}}
    protocol: TCP
  type: NodePort
  selector:
    app: nodejs-template
