apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mvn-new-template
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mvn-new-template
    spec:
      containers:
      - name: mvn-new-template
        image: registry.cn-beijing.aliyuncs.com/kaikeba/mvn-new-template:{{build_image_tag}}
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /manage/health
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "2300Mi"
        env:
        - name: PROFILE
          value: pre
        - name: APP_ENV
          value: pre
        - name: JAVA_OPTS
          value: "-Xms2g -Xmx2g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/opt/config_java_heapdump.hprof -XX:-UseLargePages -Xloggc:/var/opt/config_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M"
        - name: APP_ID
          value: mvn-new-template
        - name: SERVICE_DISCOVERY_ADDR
          value: nacos-headless.kkb-base-pre.svc.cluster.local:8848            
        - name: SERVICE_DISCOVERY_NAMESPACE
          value: 
