library('delivery')
library('kkb-flow-plugin')

delivery {
    apply plugin: "flow"
    apply plugin: "kkb_flow"
    
    config {
        category = "{{category}}"
        name = "general-template"
        release_repo = "{{release_repo}}"
        version = "1.0.0-${env.COMMIT_ID}"
        k8s_namespaces = ["dev": "kkb-dev","test":"kkb-test"]
    }
}
