apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-template
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web-template
    spec:
      containers:
      - name: web-template
        image: registry.cn-beijing.aliyuncs.com/kaikeba/web-template:{{VERSION}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
