#!/usr/bin/bash

DOCKER_IMAGE_NAME=web-template
DOCKER_INSTANCE_NAME=web-template
DOCKER_INSTANCE_PORT=80

[[ -z "$DOCKER_REGISTRY_URL" ]] && DOCKER_REGISTRY_URL=192.168.100.36:1179 && DOCKER_NAME_SPACE=xiaoke
