library('delivery')
library('kkb-k8s-mos-deploy-plugin')

delivery {
    apply plugin: "flow"
    apply plugin: "kkb_k8s_mos_deploy"

    config {
        category = "{{category}}"
        name = "mvn-new-template"
        release_repo  = "{{release_repo}}"
        newArch = false 
        subdir = "{{subdir}}"
        version = "1.0.0-${env.COMMIT_ID}"
        k8s_namespaces = ["dev": "kkb-dev","test":"kkb-test"]
    }
}
