apiVersion: v1
kind: Service
metadata:
  name: general-template
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: actuator
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
  selector:
    app: general-template

