apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mvn-old-template
  namespace: kkb-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mvn-old-template
    spec:
      containers:
        - name: mvn-old-template
          image: 192.168.100.36:1179/xiaoke/mvn-old-template:{{build_image_tag}}
          ports:
            - containerPort: 7025
          readinessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 200
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "1500Mi"
          env:
            - name: PROFILE
              value: dev
            - name: APP_ENV
              value: dev
            - name: APP_ID
              value: mvn-old-template
